### ISSUE TITLE
Issue in DL_MODEL

### ISSUE THREAD

**Issue by viyoladsouz** [kinderneutron/kinderneutron-master-build#5]
**Bug title**

**Describe the bug** 
Person_detection_main.py  stops after running for a while 

**Expected behavior**
program should run continuously

**Screenshots**
(If applicable)

**Additional context**

**Comment by kinderasteroid** [comment]
@viyoladsouz Can You Try Below mentioned Code and Reach Us out here 
```
import threading
```

```
 try:
#     process_video_feed(video_feed_url)
# except Exception as e:
#     print("Error:", e)
# cv2.destroyAllWindows()
##############################################
#ser.close() 
#####################
thread1 = threading.Thread(target=process_video_feed, args=(video_feed_url,))
thread2 = threading.Thread(target=process_video_feed, args=(video_feed_url,))
thread1.start()
thread2.start()

# Wait for threads to finish

# Wait for threads to finish
thread1.join()
thread2.join()
```

comment the Try Part of Code and Create Threads and Run the Code. Hope this Works

FYI @VLBHAT31 @viyoladsouz

**Comment by kinderasteroid** [comment]
@viyoladsouz Check with [kinderneutron-master-build-patchv1](https://github.com/kinderasteroid/kinderneutron-master-build/blob/d6cbea563ac40a0f94c56d7c3f65858f4a5f69ce/Patches/API/Modified%20Camera%20Patch.py) code and Update me

**Comment by kinderasteroid** [comment]
Issue Is Sorted By making the DL_Model Code Async
